### ISSUE TITLE
expand string package

### ISSUE THREAD

**Issue by aki237** [aki237/ligo#3]
# expand string package
+ ligo package
+ packages/string/*

# Detailed Description
String package has only a handful of string manipulation functions. Yet some functions have to be added

## System details
+ Go version : all
+ cc Version : all
+ Host OS : all

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/aki237/gospace"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build227015593=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

**Comment by aki237** [comment]
- [x] `strings.HasPrefix`

- [x] `stirngs.HasSuffix`

- [x] `strings.Repeat`

- [x] `strings.Compare`

- [x] `strings.IndexOf`

- [x] `strings.Replace`

- [x] `strings.ReplaceAll`

- [x] `strings.Split`

- [x] `strings.TrimSpace`

- [x] `strings.ToLower`

- [x] `strings.ToUpper`

- [x] `strings.ToLower`

- [x] `strings.Count`

- [x] `strings.Contains`

- [x] `strings.ContainsAny`

- [x] `strings.Join`

- [x] `strings.LastIndex`

- [x] `strings.LastIndexAny`

- [x] `stirngs.SplitAfter`

- [x] `strings.SplitN`

- [x] `strings.SplitAfterN`

- [x] `strings.Trim`

- [x] `strings.TrimPrefix`

- [x] `strings.TrimSuffix`

- [x] `strings.TrimRight`

- [x] `strings.TrimLeft`

Feel free to suggest new functions if needed..

**Comment by sadliak** [comment]
Hey, I will be glad to help you :smile:

**Comment by aki237** [comment]
Sure thing, read Contributing.md for commit formats and other instructions.
Read the `doc/*` files for how to implement them. Any doubts ping me through gitter. :)

**Comment by aki237** [comment]
done!
